#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Setting the background for the i3 Window Manager
#sh ~/.fehbg &

# Loading X Resources
#[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

# Launching Redshift
pgrep redshift &> /dev/null || redshift &> /dev/null &

# exec gnome-session
# exec i3
exec startkde
# exec startxfce4
# ...or the Window Manager of your choice

