---
- name: Configuring systemd
  copy:
    src: system.conf.d
    dest: /etc/systemd
    owner: root
    group: root

- name: Configuring journald
  copy:
    src: journald.conf.d
    dest: /etc/systemd
    owner: root
    group: root

- name: Ensuring getty for tty1 is enabled
  systemd:
    name: getty@tty1.service
    enabled: yes

- name: Ensuring getty configuration directory exists
  file:
    path: /etc/systemd/system/getty@tty1.service.d
    state: directory

- name: Enabling autologin for {{ ansible_user_id }}
  template:
    src: getty-override.j2
    dest: /etc/systemd/system/getty@tty1.service.d/override.conf
    owner: root
    group: root

- name: Enabling NetworkManager
  systemd: 
    name: NetworkManager
    enabled: yes
    state: started

- name: Enabling tlp
  systemd:
    name: '{{ item }}' 
    enabled: yes
  with_items:
    - tlp
    - tlp-sleep
...
