---
- name: Upgrading System
  pacman: update_cache=yes upgrade=yes

- name: Installing reflector
  pacman: name=reflector state=present

- name: Checking if mirrorlist was updated
  command: grep -q reflector /etc/pacman.d/mirrorlist
  register: output
  ignore_errors: yes
  changed_when: False
  check_mode: no

- name: Updating the pacman mirrorlist
  command: /usr/bin/reflector -l 20 -p http --sort rate --save /etc/pacman.d/mirrorlist -c CA
  when: output.rc != 0

- name: Installing xorg server 
  pacman: name={{ item }} state=present
  with_items:
      - xorg-server
      - xorg-xinit
      - xf86-input-synaptics
      - redshift

- name: Installing networking components 
  pacman: name={{ item }} state=present
  with_items:
      - networkmanager
      - avahi

- name: Installing Plasma desktop
  pacman: name={{ item }} state=present
  with_items:
      - plasma-desktop
      - plasma-workspace
      - plasma-wayland-session
      - plasma-pa
      - plasma-nm
      - breeze
      - breeze-gtk
      - powerdevil
      - systemsettings
      - user-manager
      - kde-gtk-config

- name: Installing KDE applications
  pacman: name={{ item }} state=present
  with_items:
      - konsole
      - ksysguard
      - dolphin
      - kdeconnect
      - gwenview
      - spectacle

- name: Installing browsers
  pacman: name={{ item }} state=present
  with_items:
      - firefox
      - chromium

- name: Installing fonts
  pacman: name={{ item }} state=present
  with_items:
      - ttf-dejavu
      - ttf-droid
      - ttf-hack
      - ttf-liberation
      - noto-fonts

- name: Installing power-saving tools
  pacman: name={{ item }} state=present
  with_items:
      - thermald
      - tlp
      - x86_energy_perf_policy

- name: Installing KeePassXC
  pacman: name=keepassxc state=present

- name: Installing Linux LTS kernel
  pacman: name=linux-lts state=present
...
