---
- name: Installing reflector
  pacman: name=reflector state=present

- name: Checking if mirrorlist was updated
  shell: grep -q reflector /etc/pacman.d/mirrorlist
  register: output
  ignore_errors: yes
  changed_when: False
  check_mode: no

- name: Updating the pacman mirrorlist
  command: /usr/bin/reflector -l 20 -p http --sort rate --save /etc/pacman.d/mirrorlist
  when: output.rc != 0

- name: Upgrading System
  pacman: update_cache=yes upgrade=yes

- name: Installing xorg server 
  pacman:
    name:
      - xorg-server
      - xorg-xinit
      - xf86-input-synaptics
      - redshift
    state: present

- name: Installing networking components 
  pacman:
    name:
      - networkmanager
      - avahi
    state: present

- name: Installing Plasma desktop
  pacman:
    name:
      - plasma-desktop
      - plasma-workspace
      - plasma-pa
      - plasma-nm
      - breeze
      - breeze-gtk
      - powerdevil
      - systemsettings
      - user-manager
    state: present

- name: Installing KDE applications
  pacman:
    name:
      - konsole
      - ksysguard
      - dolphin
      - kdeconnect
    state: present

- name: Installing browsers
  pacman:
    name:
      - firefox
      - chromium
    state: present

- name: Installing fonts
  pacman:
    name:
      - ttf-dejavu
      - ttf-droid
      - ttf-hack
      - ttf-liberation
      - noto-fonts
    state: present

- name: Installing power-saving tools
  pacman:
    name:
      - thermald
      - tlp
    state: present
...
